### ISSUE TITLE
Nonstandard use of INCLUDEPATH in PIO build

### ISSUE THREAD

**Issue by cponder** [MPAS-Dev/MPAS-Release#18]
(I was told to log these PIO issues here, if this is not the right forum can you please direct me to the right one? -- thanks)

The variable INCLUDEPATH is used by the PIO cmake but is not documented in the --help output.
Ordinarily I would expect this variable to be used in the form dir1:dir2:.... which is how some of the modules on our system are setting it.
The PIO build, however, is expanding the $INCLUDEPATH directly in some of the build commands

/shared/apps/rhel-6.2/tools/cponder/OpenMPI-1.8.4/Intel-15.0_CUDA-6.5/bin/mpifort -c -DSPMD -DHAVE_MPI -DUSEMPIIO -DSYSLINUX -D_NETCDF -I/shared/apps/rhel-6.2/tools/cponder/NetCDF-Fortran-4.4.1/Intel-15.0_OpenMPI-1.8.4_CUDA-6.5/include -D_NETCDF4 -D_PNETCDF  -fPIC -march=corei7-avx -mtune=corei7-avx  -g -I/shared/apps/rhel-6.2/tools/cponder/NetCDF-Fortran-4.4.1/Intel-15.0_OpenMPI-1.8.4_CUDA-6.5/include   **/shared/apps/cuda/CUDA-v6.5.14/include/CL:/shared/apps/cuda/CUDA-v6.5.14/include** -I/shared/apps/rhel-6.2/tools/cponder/PNetCDF-1.6.0/OpenMPI-1.8.4_Intel-15.0_CUDA-6.5/include  pio_kinds.F90

and giving me the error

ifort: error #10236: File not found:  '/shared/apps/cuda/CUDA-v6.5.14/include/CL:/shared/apps/cuda/CUDA-v6.5.14/include'

Evidently it's expected here to use a form like

-I DIR1 -I DIR2 ...

I can get around the problem by unsetting the variable, which is OK for my purposes. It may be the case that the -I DIR format really is the standard convention, but I think at the very least that you ought to document that INCLUDEPATH is a settable variable in the cmake build.

**Comment by cponder** [comment]
Ok I put it in the PIO mailing-list:

https://groups.google.com/forum/#!topic/parallelio/FGRp144EYc4

**Comment by douglasjacobsen** [comment]
Thanks!
