### ISSUE TITLE
Mismatched argument lists to nf90_create in PIO build

### ISSUE THREAD

**Issue by cponder** [MPAS-Dev/MPAS-Release#19]
(I was told to log these PIO issues here, if this is not the right forum can you please direct me to the right one? -- thanks)

I'm building PIO 1.7.1 with the following components

NetCDF 4.3.3-rc2  (the 4.3.2 had problems)
NetCDF-Fortran 4.4.1
PNetCDF 1.6.0
OpenMPI 1.8.4

and running into a parameter mismatch with calls to the nf90_create function.
This happens with the following compilers

Intel 15.0
GCC 4.8.4
PGI 15.1

so I don't think this is an issue specific to any compiler.
I'm getting this compilation error regarding the comm & info arguments to the nf90_create function

    ionf_mod.F90(82): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [COMM]
                   comm=File%iosystem%io_comm, info=File%iosystem%info)
    ---------------^
    ionf_mod.F90(82): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [INFO]
                   comm=File%iosystem%io_comm, info=File%iosystem%info)
    -------------------------------------------^

for example; here is one of the code snippets

    65 #ifdef _NETCDF
    66 #ifdef _NETCDF4
          ......
    77 #ifdef _MPISERIAL
    78           ierr = nf90_create(fname, nmode , File%fh)
    79 #else
    80           nmode = ior(nmode,NF90_MPIIO)
    81           ierr = nf90_create(fname, nmode, File%fh, &
    82                comm=File%iosystem%io_comm, info=File%iosystem%info)
    83 #endif

I'm using the flags

    FLAGS+=" --enable-pnetcdf"
    FLAGS+=" --enable-netcdf4"
    FLAGS+=" --enable-netcdf"

The PIO website says to use the first one, and the second two should either be on by default or auto-detected:

    http://www.cesm.ucar.edu/models/pio/install.html

What I'm *NOT* enabling is the --enable-mpiserial and the instructions do not say to do this.
I don't see declarations of nf90_create under either NetCDF-4.3.3-rc3 or PNetCDF-1.6.0; here is what I found under NetCDF-Fortran-4.4.1 in fortran/netcdf4_file.f90:

    77 function nf90_create(path, cmode, ncid, initialsize, chunksize, cache_size, &
    78      cache_nelems, cache_preemption, comm, info)
    79   implicit none
    80   character (len = *), intent(in) :: path
    81   integer, intent(in) :: cmode
    82   integer, intent(out) :: ncid
    83   integer, optional, intent(in) :: initialsize
    84   integer, optional, intent(inout) :: chunksize
    85   integer, optional, intent(in) :: cache_size, cache_nelems
    86   integer, optional, intent(in) :: cache_preemption
    87   integer, optional, intent(in) :: comm, info

The parameter-list here doesn't line up with what's in the ionf_mod.F90 file.

**Comment by cponder** [comment]
Here are three possibilities I can think of:
1. Is  --enable-mpiserial the only mode that works right now?
2. Does NetCDF-Fortran-4.4.1 define the **nf90_create** differently than the version you are used to building against?
3. When I built NetCDF/PNetCDF/NetCDF-Fortran libraries, was there a flag I needed to use to generate a compatible definition of nf90_create?

**Comment by douglasjacobsen** [comment]
@cponder Are you trying to build MPAS? I think if these issues are only related to PIO, you should be reporting them here: https://code.google.com/p/parallelio/

**Comment by cponder** [comment]
Ok, I moved it over here:

https://groups.google.com/forum/#!topic/parallelio/XW0R4zCOjFQ

**Comment by douglasjacobsen** [comment]
Thanks!
