### ISSUE TITLE
Problem building PIO2 dependency

### ISSUE THREAD

**Issue by hellyj** [MPAS-Dev/MPAS-Release#24]
Aloha. I'm attempting to build MPAS dependencies using Intel compilers and have gotten through HDF5, netCDF4, netCDF4-Fortran, parallel-netcdf and am now attempting to build ParallelIO-pio2_2_1 using the following script.

CC=mpicc FC=mpif90 cmake -DPnetCDF_PATH=/home/hellyj/src/parallel-netcdf-1.8.1/Build \
                            -DNetCDF_C_PATH=/home/hellyj/src/netcdf-4.4-parallel \
                            -DNetCDF_Fortran_PATH=/home/hellyj/src/netcdf-4.4-parallel \
                             /home/hellyj/src/ParallelIO-pio2_2_1

This is the result.

./cmake-command.bash
-- MPI Fortran module verified and enabled.
-- Using internal GPTL C library for timing
-- MPIIO failed verification and therefore disabled.
-- MPI Fortran module verified and enabled.
-- Using internal GPTL Fortran library for timing
-- Could NOT find MPE_C (missing:  MPE_C_LIBRARY MPE_C_INCLUDE_DIR)
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hellyj/src/ParallelIO-pio2_2_1

It complains about MPIIO but I don't know what that implies or how to correct it.  When I try to compile with

make

I get the following:

[hellyj@comet-ln3 ParallelIO-pio2_2_1]$ make
[  3%] Building Fortran object src/gptl/CMakeFiles/gptl.dir/perf_utils.F90.o
/home/hellyj/src/ParallelIO-pio2_2_1/src/gptl/perf_utils.F90(15): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MPI]
  use mpi

------^
/home/hellyj/src/ParallelIO-pio2_2_1/src/gptl/perf_utils.F90(135): error #6404: This name does not have a type, and must have an explicit type.   [MPI_COMM_WORLD]
   call mpi_abort(MPI_COMM_WORLD,0,ierr)
------------------^
/home/hellyj/src/ParallelIO-pio2_2_1/src/gptl/perf_utils.F90(190): error #6404: This name does not have a type, and must have an explicit type.   [MPI_SUCCESS]
   if (rcode /= MPI_SUCCESS) then
----------------^
/home/hellyj/src/ParallelIO-pio2_2_1/src/gptl/perf_utils.F90(182): error #6279: A specification expression object must be a dummy argument, a COMMON block object, or an object accessible through host or use association.   [MPI_MAX_ERROR_STRING]
   character(MPI_MAX_ERROR_STRING)  :: lstring
-------------^
/home/hellyj/src/ParallelIO-pio2_2_1/src/gptl/perf_utils.F90(182): error #6404: This name does not have a type, and must have an explicit type.   [MPI_MAX_ERROR_STRING]
   character(MPI_MAX_ERROR_STRING)  :: lstring
-------------^
/home/hellyj/src/ParallelIO-pio2_2_1/src/gptl/perf_utils.F90(275): error #6404: This name does not have a type, and must have an explicit type.   [MPI_INTEGER]
   call MPI_BCAST(vec,lsize,MPI_INTEGER,0,comm,ierr)
----------------------------^
/home/hellyj/src/ParallelIO-pio2_2_1/src/gptl/perf_utils.F90(307): error #6404: This name does not have a type, and must have an explicit type.   [MPI_LOGICAL]
   call MPI_BCAST(vec,lsize,MPI_LOGICAL,0,comm,ierr)
----------------------------^
compilation aborted for /home/hellyj/src/ParallelIO-pio2_2_1/src/gptl/perf_utils.F90 (code 1)
make[3]: *** [src/gptl/CMakeFiles/gptl.dir/perf_utils.F90.o] Error 1
make[2]: *** [src/gptl/CMakeFiles/gptl.dir/perf_utils.F90.o.provides] Error 2
make[1]: *** [src/gptl/CMakeFiles/gptl.dir/all] Error 2
make: *** [all] Error 2

So it looks like MPIIO might be implicated although I can't tell.  Any suggestions would be helpful.

Mahalo.
J.

**Comment by mgduda** [comment]
In the current (v5.1) release of MPAS, support for the PIO 2.x library isn't working, and instead, you'll need to use PIO 1.x. We have the most experience with PIO 1.7.1 and 1.9.23. Here are the steps that I use to install all library dependencies:
```bash
#!/bin/bash

#
# Sources for all libraries used in this script can be found at
# http://www2.mmm.ucar.edu/people/duda/files/mpas/sources/ 
#

# Where to find sources for libraries
export LIBSRC=/sysdisk1/duda/io_library_sources

# Where to install libraries
export LIBBASE=/sysdisk1/duda/mpas_io

# Compilers
export SERIAL_FC=gfortran
export SERIAL_F77=gfortran
export SERIAL_CC=gcc
export SERIAL_CXX=g++
export MPI_FC=mpif90
export MPI_F77=mpif77
export MPI_CC=mpicc
export MPI_CXX=mpicxx


########################################
# MPICH
########################################
tar xzvf ${LIBSRC}/mpich-3.1.3.tar.gz
cd mpich-3.1.3
export CC=$SERIAL_CC
export CXX=$SERIAL_CXX
export F77=$SERIAL_F77
export FC=$SERIAL_FC
./configure --prefix=${LIBBASE}
make
make check
make install
cd ..

########################################
# cmake
########################################
tar xzvf ${LIBSRC}/cmake-3.4.0-rc3.tar.gz
cd cmake-3.4.0-rc3
./bootstrap --prefix=${LIBBASE}
gmake
gmake install
export PATH=${LIBBASE}/bin:$PATH
cd ..

########################################
# zlib
########################################
tar xzvf ${LIBSRC}/zlib-1.2.8.tar.gz
cd zlib-1.2.8
./configure --prefix=${LIBBASE}
make
make install
cd ..

########################################
# HDF5
########################################
tar xjvf ${LIBSRC}/hdf5-1.8.14.tar.bz2
cd hdf5-1.8.14
export FC=$MPI_FC
export CC=$MPI_CC
export CXX=$MPI_CXX
./configure --prefix=${LIBBASE} --enable-parallel --with-zlib=${LIBBASE} --enable-fortran
make
make check
make install
cd ..

########################################
# Parallel-netCDF
########################################
tar xjvf ${LIBSRC}/parallel-netcdf-1.7.0.tar.bz2
cd parallel-netcdf-1.7.0
export CC=$SERIAL_CC
export CXX=$SERIAL_CXX
export F77=$SERIAL_F77
export FC=$SERIAL_FC
export MPICC=$MPI_CC
export MPICXX=$MPI_CXX
export MPIF77=$MPI_F77
export MPIF90=$MPI_FC
./configure --prefix=${LIBBASE}
make
make testing
make install
export PNETCDF=${LIBBASE}
cd ..

########################################
# netCDF (C library)
########################################
tar xzvf ${LIBSRC}/netcdf-4.4.0.tar.gz
cd netcdf-4.4.0
export CPPFLAGS="-I${LIBBASE}/include"
export LDFLAGS="-L${LIBBASE}/lib"
export LIBS="-lhdf5_hl -lhdf5 -lz -ldl"
export LD_LIBRARY_PATH=${LIBBASE}/lib:$LD_LIBRARY_PATH
export CC=$MPI_CC
./configure --prefix=${LIBBASE} --disable-dap --enable-netcdf4 --enable-pnetcdf --enable-parallel-tests --disable-shared
make
make check
make install
export NETCDF=${LIBBASE}
cd ..

########################################
# netCDF (Fortran interface library)
########################################
tar xzvf ${LIBSRC}/netcdf-fortran-4.4.3.tar.gz
cd netcdf-fortran-4.4.3
export FC=$MPI_FC
export F77=$MPI_F77
export LIBS="-lnetcdf ${LIBS}"
./configure --prefix=${LIBBASE} --enable-parallel-tests --disable-shared
make
make check
make install
cd ..

########################################
# PIO
########################################
tar xzvf ${LIBSRC}/pio1_9_23.tar.gz
cd ParallelIO-pio1_9_23
cd pio
export PIOSRC=`pwd`
git clone https://github.com/PARALLELIO/genf90.git bin
git clone https://github.com/CESM-Development/CMake_Fortran_utils.git cmake
cd ../..
pushd $LIBBASE
mkdir pio-1.9.23
cd pio-1.9.23
cmake -DNETCDF_C_DIR=$NETCDF -DNETCDF_Fortran_DIR=$NETCDF -DPNETCDF_DIR=$PNETCDF -DCMAKE_VERBOSE_MAKEFILE=1 $PIOSRC
make
export PIO=`pwd`
popd

########################################
# Other environment vars needed by MPAS
########################################
export MPAS_EXTERNAL_LIBS="-L${LIBBASE}/lib -lhdf5_hl -lhdf5 -ldl -lz"
export MPAS_EXTERNAL_INCLUDES="-I${LIBBASE}/include"
```
Some adaptation of these steps may work for the Intel compilers, too.

**Comment by hellyj** [comment]
Thanks. Much appreciated.

**Comment by soto97** [comment]
@mgduda These are really helpful instructions. 

I went to `http://www2.mmm.ucar.edu/people/duda/files/mpas/sources/` and copied your `iolib_installation.sh` script, changing the directories for my setup. I then used the same exact source code versions that you use in that script (which is slightly different from the example above) in the same order to compile the code and libraries. Unfortunately, I keep running into an error I don't know how to solve nor understand. When I run the `./config` command for the HDF5 library, I get the following message:

```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking shell variables initial values... done
checking if basename works... yes
checking if xargs works... yes
checking for cached host... none
checking for config x86_64-unknown-linux-gnu... no
checking for config x86_64-unknown-linux-gnu... no
checking for config unknown-linux-gnu... no
checking for config unknown-linux-gnu... no
checking for config x86_64-linux-gnu... no
checking for config x86_64-linux-gnu... no
checking for config x86_64-unknown... no
checking for config linux-gnu... found
compiler 'mpicc' is GNU gcc-4.8.5
checking for config ./config/site-specific/host-eurus.boulder.swri.edu... no
checking for config ./config/site-specific/host-boulder.swri.edu... no
checking for config ./config/site-specific/host-swri.edu... no
checking for config ./config/site-specific/host-edu... no
checking for gcc... mpicc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/home/asoto/mpas_libraries/io_library_sources/hdf5-1.8.19':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

When I got to the `config.log` file, I find the following error message:
```
configure:4570: ./conftest
./conftest: error while loading shared libraries: libmpi.so.12: cannot open shared object file: No such file or directory
configure:4574: $? = 127
configure:4581: error: in `/home/asoto/mpas_libraries/io_library_sources/hdf5-1.8.19':
configure:4583: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

The problem is that `libmpi.so.12` **does** exist and is placed exactly where it's supposed to be. Does anyone have any idea why this is failing?

I am running on a CentOS system with the following details:
```
Linux version 3.10.0-693.5.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) )
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
```

**Comment by mgduda** [comment]
@soto97 Can you verify that the path to `libmpi.so.12` is included in the `LD_LIBRARY_PATH` environment variable?

**Comment by soto97** [comment]
That was it. I thought the `LD_LIBRARY_PATH` was set early in the script, but apparently I had messed that up. Once I set it at the right point, I got past this error. Thanks.
